from __future__ import annotations

from typing import Any

SETTINGS_FIELDS: list[dict[str, Any]] = [
    {
        "name": "gateway_host",
        "label": "Адрес bind",
        "source": "env",
        "restart": True,
        "help": "Адрес, на котором процесс serve слушает REST, консоль и /mcp. Нужен до старта: GATEWAY_HOST или флаг --host. В UI не меняется.",
    },
    {
        "name": "gateway_port",
        "label": "Порт",
        "source": "env",
        "restart": True,
        "help": "Порт REST-консоли и MCP HTTP. GATEWAY_PORT или --port. Смена — перезапуск процесса.",
    },
    {
        "name": "gateway_data_dir",
        "label": "Каталог данных",
        "source": "env",
        "restart": True,
        "help": "Куда шлюз пишет console.json: базы, операторы, настройки. GATEWAY_DATA_DIR. Без каталога настройки после рестарта не сохранятся.",
    },
    {
        "name": "admin_bootstrap_token",
        "label": "Токен первого входа",
        "source": "env",
        "secret": True,
        "restart": False,
        "help": "Секрет первого входа в админку (ADMIN_BOOTSTRAP_TOKEN). После заведения оператора входите логином; токен оставьте как аварийный ключ.",
    },
    {
        "name": "onec_base_url",
        "label": "URL базы по умолчанию",
        "source": "ui",
        "restart": False,
        "help": "Корень слоя A без /v1. Мок: http://127.0.0.1:18080. Живая 1С: http(s)://{host}/{ib}/hs/mcp. Задаётся карточкой базы.",
    },
    {
        "name": "onec_token",
        "label": "Токен базы по умолчанию",
        "source": "ui",
        "secret": True,
        "restart": False,
        "help": "Bearer клиента интеграции к этой публикации 1С. Plaintext один раз из обработки «Администрирование коннектора», не SHA-256.",
    },
    {
        "name": "onec_timeout_seconds",
        "label": "Таймаут до 1С, сек",
        "source": "ui",
        "restart": False,
        "help": "Сколько шлюз ждёт ответ HTTP-сервиса мкпAPI. Слишком малое значение рвёт длинные отчёты — их лучше уводить в /v1/job.",
    },
    {
        "name": "tenant",
        "label": "База по умолчанию",
        "source": "ui",
        "restart": False,
        "help": "id базы, если агент не прислал X-Tenant и не пошёл в /t/{id}/v1/…",
    },
    {
        "name": "onec_tenants",
        "label": "Карта баз (служебное)",
        "source": "ui",
        "restart": False,
        "help": "Служебная CSV/JSON карта id=url. Редактируйте список баз на вкладке «Базы 1С», не это поле.",
    },
    {
        "name": "meta_cache_ttl_seconds",
        "label": "TTL кэша meta, сек",
        "source": "ui",
        "restart": False,
        "help": "Кэш ответов /v1/meta* на шлюзе. 0 — не кэшировать. Выборка data_*, отчёты и запросы не кэшируются.",
    },
    {
        "name": "onec_preset",
        "label": "Пресет типовой",
        "source": "ui",
        "restart": False,
        "help": "auto | ut11 | ka2 | erp2 | bp30 | none. Влияет на guide и подсказки meta_search, не на состав объектов 1С.",
    },
    {
        "name": "rate_limit_per_minute",
        "label": "Лимит запросов / мин",
        "source": "ui",
        "restart": False,
        "help": "Скользящее окно 60 с по Bearer или IP. 0 — выключить. /health, /ready и /console не считаются.",
    },
    {
        "name": "mcp_http_path",
        "label": "Путь MCP HTTP",
        "source": "ui",
        "restart": True,
        "help": "Путь streamable HTTP на процессе serve (обычно /mcp). Смена требует перезапуска шлюза.",
    },
    {
        "name": "otel_exporter_otlp_endpoint",
        "label": "OTLP endpoint",
        "source": "ui",
        "restart": True,
        "help": "Экспорт трасс. Пусто — no-op. Нужен extra pip install 'onecmcp[otel]'. Смена — перезапуск.",
    },
]

DOCS_PAGES: list[dict[str, str]] = [
    {"id": "index", "title": "Главная", "group": "Начало", "file": "index.md"},
    {"id": "architecture", "title": "Архитектура", "group": "Начало", "file": "architecture.md"},
    {"id": "compatibility", "title": "Совместимость", "group": "Начало", "file": "compatibility.md"},
    {"id": "pilots", "title": "Пилот", "group": "Начало", "file": "pilots.md"},
    {"id": "install", "title": "Установка", "group": "Установка", "file": "install.md"},
    {"id": "install/mock", "title": "Контур без 1С", "group": "Установка", "file": "install/mock.md"},
    {"id": "install/extension", "title": "Расширение и публикация", "group": "Установка", "file": "install/extension.md"},
    {"id": "install/containers", "title": "Docker и Helm", "group": "Установка", "file": "install/containers.md"},
    {"id": "usage", "title": "Пользование", "group": "Пользование", "file": "usage.md"},
    {"id": "usage/protocols", "title": "REST и MCP", "group": "Пользование", "file": "usage/protocols.md"},
    {"id": "usage/read", "title": "Чтение и отчёты", "group": "Пользование", "file": "usage/read.md"},
    {"id": "usage/write", "title": "Запись и dry-run", "group": "Пользование", "file": "usage/write.md"},
    {"id": "skills", "title": "Пресеты и guide", "group": "Пользование", "file": "skills.md"},
    {"id": "connect/README", "title": "Подключение агентов", "group": "Пользование", "file": "connect/README.md"},
    {"id": "admin/overview", "title": "Администрирование", "group": "Администрирование", "file": "admin/overview.md"},
    {"id": "admin/clients", "title": "Клиенты и лимиты", "group": "Администрирование", "file": "admin/clients.md"},
    {"id": "admin/access", "title": "Права и ACL", "group": "Администрирование", "file": "admin/access.md"},
    {"id": "admin/tenants", "title": "Тенанты и базы", "group": "Администрирование", "file": "admin/tenants.md"},
    {"id": "admin/diag", "title": "Диагностика", "group": "Администрирование", "file": "admin/diag.md"},
    {"id": "admin/how-to-change", "title": "Как что-либо изменить", "group": "Администрирование", "file": "admin/how-to-change.md"},
    {"id": "reference/settings", "title": "Все настройки", "group": "Справочник", "file": "reference/settings.md"},
    {"id": "reference/cli", "title": "Команды CLI", "group": "Справочник", "file": "reference/cli.md"},
    {"id": "reference/api", "title": "HTTP и MCP", "group": "Справочник", "file": "reference/api.md"},
    {"id": "reference/extension", "title": "Объекты расширения", "group": "Справочник", "file": "reference/extension.md"},
    {"id": "reference/errors", "title": "Ошибки", "group": "Справочник", "file": "reference/errors.md"},
    {"id": "acceptance-checklist", "title": "Чек-лист приёмки", "group": "Справочник", "file": "acceptance-checklist.md"},
]
